name: hope
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  google_cloud_translation: ^0.0.4
  openai_realtime_dart: ^0.0.3+1
  cached_network_image: ^3.3.1
  speech_to_text: ^7.0.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  audio_session: ^0.1.18
  flutter_webrtc: ^0.13.0
  http: ^1.1.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.3.4
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3
  google_sign_in: ^6.3.0
  onesignal_flutter: ^5.2.8
  purchases_flutter: ^8.7.5
  logger: ^2.5.0
  fluttertoast: ^8.2.12
  jwt_decode: ^0.3.1
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  get: ^4.7.2
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  animated_flip_counter: ^0.3.4
  share_plus: ^7.2.2
  translator: ^1.0.3+1
  video_player: ^2.8.2
  chewie: ^1.7.5
  audioplayers: ^6.4.0
  intl: ^0.20.2
  modal_bottom_sheet: ^3.0.0
  toastification: ^2.3.0
  visibility_detector: ^0.4.0+2
  shimmer: ^3.0.0
  flutter_tts: ^3.8.5
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/lyrics/
